<?php

namespace Amulen\ShopBundle\Repository;

use Flowcode\ShopBundle\Repository\ProductItemFieldDataRepository as BaseProductItemFieldDataRepository;

/**
 * ProductItemFieldDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemFieldDataRepository extends BaseProductItemFieldDataRepository
{
}
