<?php

namespace Amulen\ShopBundle\Repository;

use Flowcode\ShopBundle\Repository\ProductItemFieldRepository as BaseProductItemFieldRepository;

/**
 * ProductItemFieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductItemFieldRepository extends BaseProductItemFieldRepository
{
}
