<?php

namespace Amulen\ShopBundle\Repository;

use Flowcode\ShopBundle\Repository\ProductRawMaterialRepository as BaseProductRawMaterialRepository;

/**
 * BrandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRawMaterialRepository extends BaseProductRawMaterialRepository
{
}
