services:
    amulen.shop.product:
        class: Amulen\ShopBundle\Service\ProductService
        arguments:
          - "@doctrine.orm.entity_manager"
          - "@lexik_form_filter.query_builder_updater"
